FROM openjdk:17-oracle
ENV TZ=Europe/Moscow

RUN mkdir gateway-service
WORKDIR ./gateway-service

COPY /gateway-service/jar/gateway-service-1.0.jar .

ENTRYPOINT ["java","-jar","gateway-service-1.0.jar"]